services:
  - docker
before_script:
  - if [[ ${TRAVIS_BRANCH} == master ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi

script:
  - make all
  - ./build-tests.sh
  - ./run-tests.sh

after_success:
  - if [[ ${TRAVIS_BRANCH} == master ]]; then make push; fi
